-- nodo_tienda.orders — sales order header
-- nodo_tienda.order_items — line items per order
-- nodo_tienda.order_status_history — append-only status audit trail
--
-- All three tables use Template A (admin+staff read/write).
-- order_number is auto-generated by the trigger in migration 000021.
-- product_name / variant_label are denormalized snapshots taken at order time
-- so the order history survives product renames or deletions.

-- ---------------------------------------------------------------------------
-- 1. orders
-- ---------------------------------------------------------------------------
create table if not exists nodo_tienda.orders (
  id               uuid          primary key default gen_random_uuid(),
  org_id           uuid          not null references shared.organizations(id) on delete cascade,
  order_number     text          not null,
  customer_id      uuid          references nodo_tienda.customers(id) on delete set null,
  status           text          not null default 'pending'
                   check (status in ('pending', 'confirmed', 'preparing', 'shipped', 'delivered', 'cancelled')),
  subtotal         numeric(12,2) not null default 0,
  discount         numeric(12,2) not null default 0,
  shipping_cost    numeric(12,2) not null default 0,
  tax              numeric(12,2) not null default 0,
  total            numeric(12,2) not null default 0,
  shipping_address jsonb,
  notes            text,
  deleted_at       timestamptz,
  created_at       timestamptz   not null default now(),
  updated_at       timestamptz   not null default clock_timestamp(),
  unique (org_id, order_number)
);

create index if not exists orders_org_id_idx      on nodo_tienda.orders (org_id);
create index if not exists orders_customer_id_idx on nodo_tienda.orders (customer_id);
create index if not exists orders_org_status_idx  on nodo_tienda.orders (org_id, status);
create index if not exists orders_org_created_idx on nodo_tienda.orders (org_id, created_at desc);

create trigger set_updated_at
  before update on nodo_tienda.orders
  for each row
  execute function nodo_tienda.set_updated_at();

alter table nodo_tienda.orders enable row level security;

create policy "org_select" on nodo_tienda.orders
  for select to authenticated
  using (
    org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  );

create policy "org_insert" on nodo_tienda.orders
  for insert to authenticated
  with check (
    org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  );

create policy "org_update" on nodo_tienda.orders
  for update to authenticated
  using (
    org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  )
  with check (
    org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  );

create policy "org_delete" on nodo_tienda.orders
  for delete to authenticated
  using (
    org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  );

-- ---------------------------------------------------------------------------
-- 2. order_items
-- ---------------------------------------------------------------------------
create table if not exists nodo_tienda.order_items (
  id            uuid          primary key default gen_random_uuid(),
  org_id        uuid          not null references shared.organizations(id) on delete cascade,
  order_id      uuid          not null references nodo_tienda.orders(id) on delete cascade,
  product_id    uuid          not null references nodo_tienda.products(id) on delete restrict,
  variant_id    uuid          references nodo_tienda.product_variants(id) on delete restrict,
  product_name  text          not null,
  variant_label text,
  quantity      integer       not null check (quantity > 0),
  unit_price    numeric(12,2) not null,
  subtotal      numeric(12,2) not null,
  created_at    timestamptz   not null default now()
);

create index if not exists order_items_org_id_idx  on nodo_tienda.order_items (org_id);
create index if not exists order_items_order_id_idx on nodo_tienda.order_items (order_id);

alter table nodo_tienda.order_items enable row level security;

create policy "org_select" on nodo_tienda.order_items
  for select to authenticated
  using (
    org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  );

create policy "org_insert" on nodo_tienda.order_items
  for insert to authenticated
  with check (
    org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  );

create policy "org_update" on nodo_tienda.order_items
  for update to authenticated
  using (
    org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  )
  with check (
    org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  );

create policy "org_delete" on nodo_tienda.order_items
  for delete to authenticated
  using (
    org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  );

-- ---------------------------------------------------------------------------
-- 3. order_status_history — append-only audit trail
--    No org_id column; RLS pivots through orders table.
-- ---------------------------------------------------------------------------
create table if not exists nodo_tienda.order_status_history (
  id         uuid        primary key default gen_random_uuid(),
  order_id   uuid        not null references nodo_tienda.orders(id) on delete cascade,
  status     text        not null,
  notes      text,
  changed_by uuid        references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists order_status_history_order_id_idx on nodo_tienda.order_status_history (order_id);

alter table nodo_tienda.order_status_history enable row level security;

create policy "org_select" on nodo_tienda.order_status_history
  for select to authenticated
  using (
    exists (
      select 1 from nodo_tienda.orders o
      where o.id = order_id
        and o.org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    )
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  );

create policy "org_insert" on nodo_tienda.order_status_history
  for insert to authenticated
  with check (
    exists (
      select 1 from nodo_tienda.orders o
      where o.id = order_id
        and o.org_id = ((select auth.jwt()) -> 'app_metadata' ->> 'org_id')::uuid
    )
    and (select auth.jwt()) -> 'app_metadata' ->> 'role' in ('admin', 'staff')
  );

-- No UPDATE or DELETE: status history is append-only.
