export const MEDICAL_EXAMS = [
  { id: "hemograma", name: "Hemograma completo", category: "Laboratorio" },
  { id: "glucemia", name: "Glucemia en ayunas", category: "Laboratorio" },
  { id: "perfil-lipidico", name: "Perfil lipídico", category: "Laboratorio" },
  { id: "tsh", name: "TSH / T4 libre", category: "Laboratorio" },
  { id: "creatinina", name: "Creatinina / Urea", category: "Laboratorio" },
  { id: "transaminasas", name: "Transaminasas (ALT/AST)", category: "Laboratorio" },
  { id: "orina", name: "Urocultivo y sedimento", category: "Laboratorio" },
  { id: "pcr", name: "Proteína C reactiva", category: "Laboratorio" },
  { id: "rx-torax", name: "Radiografía de tórax PA", category: "Imagenología" },
  { id: "rx-columna", name: "Radiografía de columna", category: "Imagenología" },
  { id: "eco-abdominal", name: "Ecografía abdominal", category: "Imagenología" },
  { id: "eco-tiroides", name: "Ecografía tiroidea", category: "Imagenología" },
  { id: "eco-pelvica", name: "Ecografía pélvica", category: "Imagenología" },
  { id: "tac-craneo", name: "TAC de cráneo", category: "Imagenología" },
  { id: "tac-torax", name: "TAC de tórax", category: "Imagenología" },
  { id: "rm-columna", name: "Resonancia magnética de columna", category: "Imagenología" },
  { id: "ecg", name: "Electrocardiograma", category: "Cardiología" },
  { id: "holter", name: "Holter 24 horas", category: "Cardiología" },
  { id: "ergometria", name: "Ergometría", category: "Cardiología" },
  { id: "espirometria", name: "Espirometría", category: "Neumonología" },
  { id: "endoscopia", name: "Endoscopía digestiva alta", category: "Gastroenterología" },
  { id: "colonoscopia", name: "Colonoscopía", category: "Gastroenterología" },
  { id: "mamografia", name: "Mamografía bilateral", category: "Imagenología" },
  { id: "densitometria", name: "Densitometría ósea", category: "Imagenología" },
  { id: "eco-doppler", name: "Eco-Doppler carotídeo", category: "Imagenología" },
  { id: "rx-rodilla", name: "Radiografía de rodilla", category: "Imagenología" },
  { id: "vit-d", name: "Vitamina D (25-OH)", category: "Laboratorio" },
  { id: "hba1c", name: "Hemoglobina glicosilada (HbA1c)", category: "Laboratorio" },
  { id: "psa", name: "PSA total", category: "Laboratorio" },
  { id: "test-embarazo", name: "Beta-HCG (test embarazo)", category: "Laboratorio" },
  { id: "electroencefalograma", name: "Electroencefalograma", category: "Neurología" },
  { id: "potenciales-evocados", name: "Potenciales evocados", category: "Neurología" },
  { id: "consulta-cardio", name: "Consulta cardiología", category: "Interconsulta" },
  { id: "consulta-digestivo", name: "Consulta gastroenterología", category: "Interconsulta" },
  { id: "ionograma", name: "Ionograma (Na, K, Cl)", category: "Laboratorio" },
  { id: "acido-urico", name: "Ácido úrico", category: "Laboratorio" },
  { id: "colesterol-total", name: "Colesterol total y fracciones", category: "Laboratorio" },
  { id: "trigliceridos", name: "Triglicéridos", category: "Laboratorio" },
  { id: "hepatograma", name: "Hepatograma completo", category: "Laboratorio" },
  { id: "coagulograma", name: "Coagulograma", category: "Laboratorio" },
  { id: "ferritina", name: "Ferritina / Hierro sérico", category: "Laboratorio" },
  { id: "b12-folato", name: "Vitamina B12 y ácido fólico", category: "Laboratorio" },
  { id: "orina-completa", name: "Orina completa", category: "Laboratorio" },
  { id: "coprocultivo", name: "Coprocultivo", category: "Laboratorio" },
  { id: "hepatitis", name: "Serología hepatitis B y C", category: "Laboratorio" },
  { id: "hiv", name: "HIV (ELISA)", category: "Laboratorio" },
  { id: "vdrl", name: "VDRL / RPR", category: "Laboratorio" },
  { id: "eco-renal", name: "Ecografía renal y vías urinarias", category: "Imagenología" },
  { id: "eco-mama", name: "Ecografía mamaria", category: "Imagenología" },
  { id: "eco-partes-blandas", name: "Ecografía de partes blandas", category: "Imagenología" },
  { id: "rx-hombro", name: "Radiografía de hombro", category: "Imagenología" },
  { id: "rx-mano", name: "Radiografía de mano", category: "Imagenología" },
  { id: "rx-pie", name: "Radiografía de pie", category: "Imagenología" },
  { id: "tac-abdomen", name: "TAC de abdomen", category: "Imagenología" },
  { id: "rm-rodilla", name: "Resonancia magnética de rodilla", category: "Imagenología" },
  { id: "rm-cerebro", name: "Resonancia magnética de cerebro", category: "Imagenología" },
  { id: "mapa", name: "MAPA 24 horas", category: "Cardiología" },
  { id: "ecocardiograma", name: "Ecocardiograma Doppler", category: "Cardiología" },
  { id: "prueba-esfuerzo", name: "Prueba de esfuerzo", category: "Cardiología" },
  { id: "polisomnografia", name: "Polisomnografía", category: "Neumonología" },
  { id: "rx-senos", name: "Radiografía de senos paranasales", category: "Imagenología" },
  { id: "audiometria", name: "Audiometría tonal", category: "Otorrinolaringología" },
  { id: "consulta-neuro", name: "Consulta neurología", category: "Interconsulta" },
  { id: "consulta-trauma", name: "Consulta traumatología", category: "Interconsulta" },
  { id: "consulta-derma", name: "Consulta dermatología", category: "Interconsulta" },
  { id: "consulta-gine", name: "Consulta ginecología", category: "Interconsulta" },
  { id: "papanicolaou", name: "Papanicolaou", category: "Ginecología" },
  { id: "colposcopia", name: "Colposcopía", category: "Ginecología" },
] as const;

export const LIFECYCLE_LABELS = {
  en_espera: "En espera",
  en_consulta: "En consulta",
  finalizada: "Finalizada",
} as const;

export const LIFECYCLE_COLORS = {
  en_espera: "bg-amber-100 text-amber-800 border-amber-200",
  en_consulta: "bg-emerald-100 text-emerald-800 border-emerald-200",
  finalizada: "bg-slate-100 text-slate-600 border-slate-200",
} as const;
