[api]
enabled = true
port = 54321
schemas = ["public", "nodo_clinica"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:5174"
additional_redirect_urls = ["http://localhost:3000"]

[storage]
enabled = true
file_size_limit = "10MiB"
